/**
 * Presales Hub — k6 Proposal Write Contention Test
 *
 * Concurrent proposal creation to measure DB write contention.
 * Identifies connection pool exhaustion, transaction deadlocks, and
 * SQLAlchemy pool timeout thresholds under parallel write load.
 *
 * Usage:
 *   k6 run load_tests/k6/proposal_write.js
 *   k6 run --vus 20 --duration 60s load_tests/k6/proposal_write.js
 *   k6 run --env BASE_URL=https://api.presaleshub.io load_tests/k6/proposal_write.js
 */
import http from "k6/http";
import { check, sleep } from "k6";
import { Rate, Trend, Counter } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8003";
const EMAIL = __ENV.DEMO_EMAIL || "arjun@sisa.demo";
const PASSWORD = __ENV.DEMO_PASSWORD || "Demo@1234";

const writeLatency = new Trend("proposal_write_ms", true);
const errorRate = new Rate("write_errors");
const poolTimeouts = new Counter("pool_timeout_503");
const validationErrors = new Counter("validation_422");

const STAGES = ["qualification", "scoping", "proposal", "negotiation"];
const CLIENTS = ["Acme Corp", "BankCo", "HealthPlus", "RetailX", "LogiTech", "FinServe"];

export const options = {
  stages: [
    { duration: "10s", target: 5 },   // warm up
    { duration: "30s", target: 15 },  // ramp to concurrent write load
    { duration: "20s", target: 15 },  // sustain peak
    { duration: "10s", target: 0 },   // ramp down
  ],
  thresholds: {
    proposal_write_ms: ["p(95)<2000"],   // writes should complete < 2s at p95
    write_errors: ["rate<0.05"],          // < 5% error rate
    http_req_failed: ["rate<0.05"],
  },
};

export function setup() {
  const res = http.post(
    `${BASE_URL}/auth/login`,
    JSON.stringify({ email: EMAIL, password: PASSWORD }),
    { headers: { "Content-Type": "application/json" } },
  );
  if (res.status !== 200) {
    console.error(`Login failed: ${res.status}`);
    return { token: null };
  }
  return { token: JSON.parse(res.body).access_token };
}

export default function (data) {
  if (!data.token) {
    errorRate.add(1);
    sleep(1);
    return;
  }

  const headers = {
    Authorization: `Bearer ${data.token}`,
    "Content-Type": "application/json",
  };

  const randStr = Math.random().toString(36).substring(2, 7);
  const payload = {
    title: `k6 write test ${randStr}`,
    opportunity_name: `${CLIENTS[Math.floor(Math.random() * CLIENTS.length)]} Engagement`,
    stage: STAGES[Math.floor(Math.random() * STAGES.length)],
    value: Math.floor(Math.random() * 450_000) + 50_000,
    description: `Generated by k6 proposal_write.js at ${new Date().toISOString()}`,
  };

  const res = http.post(`${BASE_URL}/api/proposals`, JSON.stringify(payload), { headers });
  writeLatency.add(res.timings.duration);

  if (res.status === 200 || res.status === 201) {
    check(res, { "proposal created": () => true });
  } else if (res.status === 503) {
    poolTimeouts.add(1);
    errorRate.add(1);
    console.warn(`Pool timeout/circuit breaker: ${res.body?.substring(0, 100)}`);
  } else if (res.status === 422) {
    validationErrors.add(1);
    errorRate.add(1);
    console.warn(`Validation error: ${res.body?.substring(0, 200)}`);
  } else if (res.status === 401 || res.status === 403) {
    errorRate.add(1);
    console.warn(`Auth error ${res.status} — token may have expired`);
  } else {
    errorRate.add(1);
    check(res, { "unexpected status": (r) => false });
    console.error(`Unexpected ${res.status}: ${res.body?.substring(0, 100)}`);
  }

  sleep(0.2 + Math.random() * 0.3); // 200–500ms jitter between writes
}

export function handleSummary(data) {
  const p50 = data.metrics?.proposal_write_ms?.values?.["p(50)"] ?? "N/A";
  const p95 = data.metrics?.proposal_write_ms?.values?.["p(95)"] ?? "N/A";
  const p99 = data.metrics?.proposal_write_ms?.values?.["p(99)"] ?? "N/A";
  const timeouts = data.metrics?.pool_timeout_503?.values?.count ?? 0;

  console.log("\n  Proposal Write Contention Results:");
  console.log(`  Write latency p50: ${typeof p50 === "number" ? p50.toFixed(0) : p50}ms`);
  console.log(`  Write latency p95: ${typeof p95 === "number" ? p95.toFixed(0) : p95}ms`);
  console.log(`  Write latency p99: ${typeof p99 === "number" ? p99.toFixed(0) : p99}ms`);
  console.log(`  Pool timeouts (503): ${timeouts}`);
  if (timeouts > 0) {
    console.log("  ⚠ DB connection pool exhaustion detected — consider increasing pool_size");
  }
  return {};
}
